version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: flowsync-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: flowsync_user
      POSTGRES_PASSWORD: flowsync_password
      POSTGRES_DB: flowsync_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
